import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class BestTestPattern
{
	public String solve(String correctAnswers, int maxLen)
	{
		int[] cnt = new int[6]; //A-F		
		int n = correctAnswers.length();
		int max = 0, maxi = 0;
		for (int i = 0; i < n; i++) {
			char c = correctAnswers.charAt(i);
			cnt[c-'A']++;
			if (cnt[c-'A'] > max) {
				max = cnt[c-'A'];
				maxi = c-'A';
			}
		}
		
		ArrayList<Integer> lett = new ArrayList<>();
		for (int i = 0; i < 6; i++) {
			if (cnt[i] > 0) lett.add(i);
		}
		int numLet = lett.size();
		maxLen = Math.min(maxLen, numLet);
		
		return "A";
		
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, int p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + p1);
		System.out.println("]");
		BestTestPattern obj;
		String answer;
		obj = new BestTestPattern();
		long startTime = System.currentTimeMillis();
		answer = obj.solve(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		int p1;
		String p2;
		
		// ----- test 0 -----
		p0 = "AACAAACBAACA";
		p1 = 5;
		p2 = "AACA";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "ABCABCAB";
		p1 = 3;
		p2 = "ABC";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "FCFBFAFDFEFCFBFEFDF";
		p1 = 4;
		p2 = "FAFB";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "EEEEEEE";
		p1 = 3;
		p2 = "E";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "AACAAACBAACA";
		p1 = 3;
		p2 = "A";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "ABCDEFABCDEFABCDEEABCDEF";
		p1 = 24;
		p2 = "ABCDEFABCDEFABCDEE";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
